### ISSUE TITLE
Sort colors by count in the library

### ISSUE THREAD

**Issue by deifactor** [Ivordir/Okolors#2]
The binary has a way to sort the output colors by frequency, but as far as I can tell the library doesn't. I'd like this because I'm intending to use okolors as a color theme generator in my own application; rnow I have to use quantette directly.

Thanks a ton for this btw :)

**Comment by Ivordir** [comment]
I see, yeah that should be relatively easy to add. I'll get around to it soon.

> Thanks a ton for this btw :)

You're welcome!

**Comment by Ivordir** [comment]
Published version `0.6.0` which added `Okolors::sort_by_frequency`  :)
