### ISSUE TITLE
Add `okolors` to Scoop Extras

### ISSUE THREAD

**Issue by oxjihun** [Ivordir/Okolors#8]
[Scoop](https://scoop.sh/) is a command-line installer for Windows. I would like to add the following manifest to the Scoop's [Extras](https://github.com/ScoopInstaller/Extras) bucket so that one can install `okolors` by running `scoop install extras/okolors`:

``` json
{
    "version": "0.8.0",
    "description": "Generate a color palette from an image using k-means clustering in the Oklab color space.",
    "homepage": "https://github.com/Ivordir/Okolors",
    "license": "MIT",
    "architecture": {
        "64bit": {
            "url": "https://github.com/Ivordir/Okolors/releases/download/v0.8.0/okolors-v0.8.0-x86_64-pc-windows-msvc.zip",
            "hash": "8caaae55302c9754ab2b9337ad1e5f9dc07916fcaed160a40dd8600c08b4de4c"
        }
    },
    "bin": "okolors.exe",
    "checkver": "github",
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/Ivordir/Okolors/releases/download/v$version/okolors-v$version-x86_64-pc-windows-msvc.zip"
            }
        }
    }
}
```

This issue was written to get confirmation prior to actually making PR on the bucket.

**Comment by Ivordir** [comment]
Sure, feel free to add it to Scoop extras! Let me know if there's issues with the installer, etc.

**Comment by oxjihun** [comment]
Recently, I noticed the following criteria written in the auto-generated issue template:

> ## Criteria
> Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have **at least 100 stars and/or 50 forks**)

Sorry, my bad! I will close this issue for now, maybe I could re-open this when enough number of stars has been achieved.
